### PR TITLE
PAGOPA-711 integration test: modified and added integration tests

### PR DESCRIPTION
**Pull request by alessio-acitelli**
#### List of Changes

- updated and added integration tests

#### Motivation and Context

- updating old tests with recent changes and adding specific tests for the new expected behavior

#### How Has This Been Tested?

- manully run in local environment 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Review by jacopocarlini — APPROVED** [review]

**Comment by jacopocarlini** [comment]
update_code

**Pull request merged**
